steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]

  # push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]

serviceAccount: "346456483095-compute@developer.gserviceaccount.com"

options:
  logging: CLOUD_LOGGING_ONLY
